export const pics = [
  // 5x5
  {
    'level': 'easy',
    'size': 5,
    'name': 'Flower',
    'pic':
      [
        [{ isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        ],
      ]
  },
  {
    'level': 'easy',
    'size': 5,
    'name': 'Dinosaur',
    'pic':
      [
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: false },
        ],
      ],
  },
  {
    'level': 'easy',
    'size': 5,
    'name': 'Car',
    'pic':
      [
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: false },
        ],
      ],
  },
  {
    'level': 'easy',
    'size': 5,
    'name': 'Snake',
    'pic':
      [
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
      ],
  },
  {
    'level': 'easy',
    'size': 5,
    'name': 'Dog',
    'pic':
      [
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: false },
        ],
        [{ isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: false },
        ]
      ],
  },
  // 10x10
  {
    'level': 'medium',
    'size': 10,
    'name': 'Question',
    'pic':
      [
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        ]
      ]
  },
  {
    'level': 'medium',
    'size': 10,
    'name': 'House',
    'pic':
      [
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
      ],
  },
  {
    'level': 'medium',
    'size': 10,
    'name': 'Postcard',
    'pic':
      [
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
      ],
  },
  {
    'level': 'medium',
    'size': 10,
    'name': 'Sheet',
    'pic':
      [
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        ],
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        ],
      ],
  },
  {
    'level': 'medium',
    'size': 10,
    'name': 'Doll',
    'pic':
      [
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        ],
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        ],
        [{ isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
      ],
  },
    //15x15
  {
    'level': 'hard',
    'size': 15,
    'name': 'Peaks',
    'pic':
      [
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        ],
      ],
  },
  {
    'level': 'hard',
    'size': 15,
    'name': 'Clover',
    'pic':
      [
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        ],
      ],
  },
  {
    'level': 'hard',
    'size': 15,
    'name': 'Sun',
    'pic':
      [
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
      ],
  },
  {
    'level': 'hard',
    'size': 15,
    'name': 'Duck',
    'pic':
      [
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        ],
        [{ isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        ],
        [{ isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        ],
      ],
  },
  {
    'level': 'hard',
    'size': 15,
    'name': 'Bulb',
    'pic':
      [
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
        [{ isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: false },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        { isShouldClick: true },
        ],
      ],
  },
]